"use client";
import { useState } from "react";
import { Activity, CircleCheckBig, Clock3, Play, Workflow } from "lucide-react";
import { PageHeading } from "@/components/page-heading";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
const initial=["Profile Processor","Job Ingestion","Requirement Extractor","Job Matcher","High-match Notification","Application Generator","Follow-up","Interview Prep","Skill Analytics","Global Error Handler"];
export default function AutomationsPage(){const [lastRun,setLastRun]=useState("4 minutes ago");return <><PageHeading title="Automations" description="Operational visibility for n8n workflows without exposing the editor." actions={<Button variant="outline" onClick={()=>setLastRun("just now")}><Play data-icon="inline-start"/>Run discovery</Button>}/><div className="mb-6 grid gap-4 md:grid-cols-3"><Card><CardHeader><CardDescription>Executions today</CardDescription><CardTitle className="text-3xl">1,284</CardTitle></CardHeader></Card><Card><CardHeader><CardDescription>Success rate</CardDescription><CardTitle className="text-3xl">99.4%</CardTitle></CardHeader></Card><Card><CardHeader><CardDescription>Last discovery</CardDescription><CardTitle className="text-xl">{lastRun}</CardTitle></CardHeader></Card></div><Card><CardHeader><CardTitle>Workflow health</CardTitle><CardDescription>Retry strategy: 30 seconds, 2 minutes, then dead-letter queue.</CardDescription></CardHeader><CardContent>{initial.map((name,i)=><div key={name} className="flex items-center gap-4 border-b py-4 last:border-b-0"><div className="flex size-9 items-center justify-center rounded-lg bg-secondary">{i===9?<Activity className="size-4"/>:<Workflow className="size-4"/>}</div><div className="flex-1"><p className="text-sm font-semibold">WF-{String(i+1).padStart(2,"0")} {name}</p><p className="mt-1 flex items-center gap-1 text-xs text-muted-foreground"><Clock3 className="size-3"/>Last run {i%2?"8m":"4m"} ago · {120+i*9}ms</p></div><Badge variant="success"><CircleCheckBig className="mr-1 size-3"/>ACTIVE</Badge></div>)}</CardContent></Card></>}

